### ISSUE TITLE
Add previous flashcard interval in practice function

### ISSUE THREAD

**Issue by justincalleja** [Maxvien/supermemo#1]
Hi :)

I haven't read the SM-2 spec or anything, but shouldn't it be `interval + flashcard.interval` in the `How to implement SuperMemo with DayJS?` section of the README?

```js
  const dueDate = dayjs(Date.now())
    .add(interval + flashcard.interval, 'day')
    .toISOString();
```

Otherwise, you're only ever adding the last interval to today's date.

Thanks

**Comment by justincalleja** [comment]
Ah wait, I see now. The assumption is that the `practice` function is called on the `dueDate` response of previous `practice` function results.

I still think it would be nice to document this with an example though. I'll send a PR soon.

**Comment by VienDinhCom** [comment]
I think I should make some changes here to make it more clear.

```ts
const dueDate = dayjs(Date.now()).add(interval, 'day').toISOString();
```
to
```ts
const practiceDate = Date.now();
const dueDate = dayjs(practiceDate).add(interval, 'day').toISOString();
```

In the real-world,  the `practiceDate` should always be `Date.now()`.
